# Generated by Django 5.1.4 on 2024-12-18 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='size',
        ),
        migrations.AlterField(
            model_name='coat',
            name='size',
            field=models.CharField(choices=[('m', 38), ('l', 40), ('xl', 42)], default='m', max_length=3),
        ),
        migrations.AlterField(
            model_name='hoodie',
            name='size',
            field=models.CharField(choices=[('m', 38), ('l', 40), ('xl', 42)], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 18, 19, 53, 9, 577641)),
        ),
        migrations.AlterField(
            model_name='pants',
            name='size',
            field=models.CharField(choices=[('m', 38), ('l', 40), ('xl', 42)], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='size',
            field=models.CharField(choices=[('m', 38), ('l', 40), ('xl', 42)], default=1, max_length=3),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.CharField(choices=[('قالب خیلی کوچک', 38), ('قالب کوچک', 39), ('قالب متوسط', 40), ('قالب بزرگ', 41), ('قالب خیلی بزرگ', 42)], default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='skirt',
            name='size',
            field=models.CharField(choices=[('m', 42), ('l', 44), ('xl', 46)], default=1, max_length=3),
        ),
    ]
