# Generated by Django 5.1.4 on 2024-12-19 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_bag_size_alter_coat_size_alter_hoodie_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 20, 0, 59, 14, 644082)),
        ),
    ]
