# Generated by Django 5.1.4 on 2025-01-10 18:36

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bag',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='coat',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='hat',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='socks',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='belt',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='coat',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='h_id',
        ),
        migrations.RemoveField(
            model_name='hoodie',
            name='h_id',
        ),
        migrations.RemoveField(
            model_name='pants',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='sh_id',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='sh_id',
        ),
        migrations.RemoveField(
            model_name='skirt',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='socks',
            name='design',
        ),
        migrations.RemoveField(
            model_name='socks',
            name='s_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_id',
        ),
        migrations.AddField(
            model_name='bag',
            name='bag_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='belt',
            name='belt_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coat',
            name='coat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hat',
            name='hat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoodie',
            name='hoodie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pants',
            name='pant_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='shirt_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoes',
            name='shoe_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skirt',
            name='skirt_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socks',
            name='socks_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 10, 22, 1, 0, 561765)),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_id',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Scarves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scarf_id', models.IntegerField()),
                ('season', models.CharField(choices=[('spring', 'بهار'), ('summer', 'تابستان'), ('autumn', 'پاییز'), ('winter', 'زمستان')], default='spring', max_length=6)),
                ('description', models.CharField(default=' ', max_length=500)),
                ('design', models.CharField(max_length=30)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Scarf',
        ),
    ]
