# Generated by Django 5.1.4 on 2025-01-10 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_product_bag_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 1, 10, 22, 8, 27, 898701)),
        ),
    ]
