# Generated by Django 5.1.4 on 2025-01-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'shop_bag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopBelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'shop_belt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'shop_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopCoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'shop_coat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopHat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'shop_hat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopHoodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.CharField(max_length=10)),
                ('hat', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'shop_hoodie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
                ('address', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'shop_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopPants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'shop_pants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('picture', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shop_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopScarf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=500)),
                ('design', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'shop_scarf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopShirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'shop_shirt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'shop_shoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopSkirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'shop_skirt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopSocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('design', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'shop_socks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nation_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'shop_user',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='belt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='coat',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='hoodie',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='scarves',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='skirt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='socks',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='Belt',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Coat',
        ),
        migrations.DeleteModel(
            name='Hat',
        ),
        migrations.DeleteModel(
            name='Hoodie',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Pants',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Scarves',
        ),
        migrations.DeleteModel(
            name='Skirt',
        ),
        migrations.DeleteModel(
            name='Socks',
        ),
        migrations.DeleteModel(
            name='Shirt',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
