# Generated by Django 5.1.4 on 2025-01-13 18:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coat_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
                ('size', models.CharField(choices=[('m', 38), ('l', 40), ('xl', 42)], default='m', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hoodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.IntegerField()),
                ('hat', models.CharField(choices=[('0', 'بدون کلاه'), ('1', 'با کلاه')], default='0', max_length=1)),
                ('description', models.CharField(default=' ', max_length=500)),
                ('size', models.CharField(choices=[('m', 38), ('l', 40), ('xl', 42)], default=1, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 1, 13, 22, 24, 48, 345857))),
                ('status', models.BooleanField(default=False)),
                ('address', models.CharField(default=' ', max_length=500)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
                ('size', models.CharField(choices=[('m', 38), ('l', 40), ('xl', 42)], default=1, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('material', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('female', 'زن'), ('male', 'مرد'), ('child', 'کودک'), ('sport', 'اسپرت')], default='sport', max_length=6)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('picture', models.ImageField(upload_to='upload/product/')),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Scarves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scarf_id', models.IntegerField()),
                ('season', models.CharField(choices=[('spring', 'بهار'), ('summer', 'تابستان'), ('autumn', 'پاییز'), ('winter', 'زمستان')], default='spring', max_length=6)),
                ('description', models.CharField(default=' ', max_length=500)),
                ('design', models.CharField(max_length=30)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
                ('size', models.CharField(choices=[('m', 38), ('l', 40), ('xl', 42)], default=1, max_length=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
                ('size', models.CharField(choices=[('قالب خیلی کوچک', 38), ('قالب کوچک', 39), ('قالب متوسط', 40), ('قالب بزرگ', 41), ('قالب خیلی بزرگ', 42)], default=1, max_length=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Skirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
                ('size', models.CharField(choices=[('m', 42), ('l', 44), ('xl', 46)], default=1, max_length=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Socks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socks_id', models.IntegerField()),
                ('description', models.CharField(default=' ', max_length=500)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nation_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='ShopBag',
        ),
        migrations.DeleteModel(
            name='ShopBelt',
        ),
        migrations.DeleteModel(
            name='ShopCategory',
        ),
        migrations.DeleteModel(
            name='ShopCoat',
        ),
        migrations.DeleteModel(
            name='ShopHat',
        ),
        migrations.DeleteModel(
            name='ShopHoodie',
        ),
        migrations.DeleteModel(
            name='ShopOrder',
        ),
        migrations.DeleteModel(
            name='ShopPants',
        ),
        migrations.DeleteModel(
            name='ShopProduct',
        ),
        migrations.DeleteModel(
            name='ShopScarf',
        ),
        migrations.DeleteModel(
            name='ShopShirt',
        ),
        migrations.DeleteModel(
            name='ShopShoes',
        ),
        migrations.DeleteModel(
            name='ShopSkirt',
        ),
        migrations.DeleteModel(
            name='ShopSocks',
        ),
        migrations.DeleteModel(
            name='ShopUser',
        ),
        migrations.AddField(
            model_name='pants',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='hoodie',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='hat',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='coat',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='belt',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='bag',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user'),
        ),
    ]
