# Generated by Django 5.1.4 on 2025-01-13 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_bag_belt_category_coat_hat_hoodie_order_pants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 22, 25, 44, 52673)),
        ),
    ]
