# Generated by Django 5.1.4 on 2025-01-13 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bag_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 22, 35, 8, 237800)),
        ),
    ]
