# Generated by Django 5.1.4 on 2025-01-17 23:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_bag_bag_id_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('national_code', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user_type', models.TextField(blank=True, null=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('pant_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scarve',
            fields=[
                ('scarf_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scarves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('shoe_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sock',
            fields=[
                ('sock_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('tshirt_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tshirts',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='pants',
            name='product',
        ),
        migrations.RemoveField(
            model_name='scarves',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='product',
        ),
        migrations.RemoveField(
            model_name='socks',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='bag',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='belt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hoodie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skirt',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Pants',
        ),
        migrations.DeleteModel(
            name='Scarves',
        ),
        migrations.DeleteModel(
            name='Shirt',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.DeleteModel(
            name='Socks',
        ),
    ]
