# Generated by Django 5.1.4 on 2025-01-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_customuser_categorie_pant_scarve_shoe_sock_tshirt_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bag',
            table='bags',
        ),
        migrations.AlterModelTable(
            name='belt',
            table='belts',
        ),
        migrations.AlterModelTable(
            name='coat',
            table='coats',
        ),
        migrations.AlterModelTable(
            name='hat',
            table='hats',
        ),
        migrations.AlterModelTable(
            name='hoodie',
            table='hoodies',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='skirt',
            table='skirts',
        ),
    ]
