# Generated by Django 5.1.4 on 2025-01-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_bag_table_alter_belt_table_alter_coat_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
